sudo: false

language: node_js
node_js:
  - "0.12.0"
  - "stable"
services: mongodb
script:
- ./node_modules/.bin/gulp
- ./node_modules/.bin/mocha test

matrix:
  allow_failures:
    - node_js: "stable"